### ISSUE TITLE
 Unhandled 'error' event   

### ISSUE THREAD

**Issue by jiangjiangflies** [codealchemist/youtube-audio-server#4]
Hi, I'm quite interested in this program but there is a problem with my installation. The errors are as follows:
`events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::80
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at Server._listen2 (net.js:1262:14)
    at listen (net.js:1298:10)
    at Server.listen (net.js:1394:5)
    at EventEmitter.listen (/usr/lib/node_modules/youtube-audio-server/node_modules/express/lib/application.js:618:24)
    at Object.listen (/usr/lib/node_modules/youtube-audio-server/src/index.js:59:7)
    at run (/usr/lib/node_modules/youtube-audio-server/src/bin.js:51:7)
    at Object.<anonymous> (/usr/lib/node_modules/youtube-audio-server/src/bin.js:57:1)
    at Module._compile (module.js:570:32)
`
I'm trying to install it on debian7 with v6.11.4.  Could you tell me how to fix it ?

**Comment by JulienLeotier** [comment]
you can run with sudo ?

**Comment by Salil999** [comment]
This just means you're already using that port for something else. Try using a different port or restart your machine.

**Comment by codealchemist** [comment]
Hopefully this is already solved :)
Thanks for your answer @Salil999 👍 

@jiangjiangflies here you have documentation about how to change default port:
https://github.com/codealchemist/youtube-audio-server#change-port

Cheers!
